### ISSUE TITLE
准备爬智联的招聘信息，折腾了一天，发现其内容是js渲染产生的

### ISSUE THREAD

**Issue by zackzhangkai** [zackzhangkai/zackzhangkai.github.io#5]
下一步需研究如何使用selenium来爬了，或者其他解决js所渲染产生的内容

**Comment by kaizamm** [comment]
今天来继续奋战，发现非ajax请求出的数据，而是在调用scrapy shell url后的response里，用view(response)看到的结果，与我们的目标页面并不一致

**Comment by kaizamm** [comment]
调其response.url在浏览器中查看，发现只有传入了一个参数，http://sou.zhaopin.com/jobs/searchresult.ashx?jl=%E6%AD%A6%E6%B1%89

**Comment by kaizamm** [comment]
在爬虫的时候，如果是爬动态的网站，对于很多内容是动态产生的， 在不断刷新，因此，不要一直死盯着一个关键字进行搜索

**Comment by kaizamm** [comment]
爬虫的时候记得allowed_domains注释掉，经常捣乱
