### ISSUE TITLE
目标

### ISSUE THREAD

**Issue by zackzhangkai** [zackzhangkai/zackzhangkai.github.io#6]
总结了下，发现要持续学习是个不简单的事。坚持一条路，然后去实践做出成绩。
###  homework
+ 利用vagrantfile一键生成devops所有组件，做到可视化

**Comment by kaizamm** [comment]
乐观、快乐、开源、价值、分享、沟通、灵性

**Comment by chinakevinguo** [comment]
哈哈，我最近正在写一个用ansible 批量部署kubernetes的东西，所有的组件都是二进制的，等我写好了，共享给你用。
