### ISSUE TITLE
关于kubernetes

### ISSUE THREAD

**Issue by zackzhangkai** [zackzhangkai/zackzhangkai.github.io#7]
参考官网用kubeadm搭建kubenetes-cluster其实是非常简单的，但一直出来不了想要的效果，且dashboard也一直有问题，经查，发现vagrant platform有bug，最后经taint 及将node结点draint后，将pod漂移至master上后，问题解决。

**Comment by kaizamm** [comment]
我 基本面栽基本面<asdfasdf>苦
